name: CI - Pruebas Unitarias

on:
  push:
    branches:
      - main    # Ejecutar cuando haya un push en la rama main
      - dev     # Ejecutar cuando haya un push en la rama dev
  pull_request:
    branches:
      - main    # Ejecutar cuando haya un pull request hacia la rama main
      - dev     # Ejecutar cuando haya un pull request hacia la rama dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test
